<?xml version="1.0"?>
<robot name="my_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="pi" value="3.1415926535897931"/>
    <xacro:property name="mass" value="10" /> 
    <xacro:property name="width" value="0.5" /> 
    <xacro:property name="length" value="0.6" />
    <xacro:property name="height" value="0.1" />
    <xacro:property name="radius" value="0.125" /> 

    <xacro:include filename="$(find my_bot)/urdf/my_bot.gazebo" />
    <xacro:include filename="$(find my_bot)/urdf/materials.xacro" />

    <link name="base_link">
        <collision>
            <geometry>
                <box size="${length} ${width} ${height}"/>
            </geometry>
        </collision>
        <visual>
            <geometry>
                <box size="${length} ${width} ${height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <inertial>
            <mass value="${mass}"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
	</inertial>
    </link>

    <xacro:macro name="wheel" params="prefix suffix ref1 ref2">
        <link name="${prefix}_${suffix}_wheel">
            <visual>
                <geometry>
                    <cylinder length="${height}" radius="${radius}"/>
                </geometry>
                <material name="black"/>
                <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${height}" radius="${radius}"/>
                </geometry>
		<origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
            </collision>
            <inertial>
                <mass value="${mass/4}"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
	    </inertial>
        </link>
        <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
            <axis xyz="0 1 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_${suffix}_wheel"/>
            <origin rpy="0 0 0" xyz="${ref1*height*2} ${ref2*height*2} -0.175"/>
        </joint>
        <gazebo reference="${prefix}_${suffix}_wheel">
            <mu1 value="200.0"/>
            <mu2 value="100.0"/>
            <kp value="10000000.0" />
            <kd value="1.0" />
            <material>Gazebo/Black</material>
        </gazebo>
        <transmission name="${prefix}_${suffix}_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${prefix}_${suffix}_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${prefix}_${suffix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>
    </xacro:macro>
    <xacro:wheel prefix="right" suffix="front" ref1="1" ref2="1"/>
    <xacro:wheel prefix="right" suffix="back" ref1="-1" ref2="1"/>
    <xacro:wheel prefix="left" suffix="front" ref1="1" ref2="-1"/>
    <xacro:wheel prefix="left" suffix="back" ref1="-1" ref2="-1"/> 

    <link name="hokuyo_link">
        <collision>
            <geometry>
                <box size="0.1 0.1 0.01"/>
            </geometry>
        </collision>
        <visual>
            <geometry>
                <box size="0.1 0.1 0.01"/>
            </geometry>
            <material name="black"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            </visual>
        <inertial>
            <mass value="1"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </link>
    <joint name="hokuyo_joint" type="fixed">
        <parent link="base_link"/>
        <child link="hokuyo_link"/>
        <origin rpy="0 0 0" xyz="0.35 0 -0.04"/>
    </joint>

    <link name="kinect_base">
        <collision>
            <geometry>
                <box size="0.05 0.1 0.1"/>
            </geometry>
	    <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <visual>
            <geometry>
                <box size="0.05 0.1 0.1"/>
            </geometry>
            <material name="black"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>
        <inertial>
            <mass value="1"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </link>
    <joint name="kinect_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="kinect_base"/>
        <origin rpy="0 0 0" xyz="0.275 0 0.1"/>
    </joint>

    <link name="kinect_link">
        <collision>
            <geometry>
                <box size="0.1 0.1 0.01"/>
            </geometry>
	    <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <visual>
            <geometry>
                <box size="0.1 0.1 0.01"/>
            </geometry>
            <material name="white"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>
        <inertial>
            <mass value="1"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </link>
    <joint name="kinect_joint" type="fixed">
        <parent link="kinect_base"/>
        <child link="kinect_link"/>
        <origin rpy="0 0 0" xyz="0.075 0 0.045"/>
    </joint>

  <!-- Hokuyo Laser -->
  <link name="hokuyo_sensor">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://my_bot/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </link>
  <joint name="hokuyo_sensor_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 0.04" rpy="0 0 0"/>
    <parent link="hokuyo_link"/>
    <child link="hokuyo_sensor"/>
  </joint>

  <link name="kinect_sensor">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://my_bot/meshes/kinect.dae"/>
      </geometry>
    </visual>
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </link>   
  <joint name="kinect_sensor_joint" type="fixed">
    <origin xyz="0.05 0 0.05" rpy="0 0 0"/>
    <parent link="kinect_link"/>
    <child link="kinect_sensor"/>
  </joint>

</robot>
