my_bot:
  gazebo_ros_control/pid_gains:
    right_front_wheel_joint: {p: 10.0, i: 0.0, d: 0.5}
    right_back_wheel_joint: {p: 10.0, i: 0.0, d: 0.5}
    left_front_wheel_joint: {p: 10.0, i: 0.0, d: 0.5}
    left_back_wheel_joint: {p: 10.0, i: 0.0, d: 0.5}
