# The joint state controller handles publishing transforms for any moving joints
 
my_bot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  left1_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left2_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_back_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: right_front_wheel_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}
  right2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: right_back_wheel_joint
    pid: {p: 100.0, i: 0.1, d: 10.0} 
