# The joint state controller handles publishing transforms for any moving joints
 
my_bot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
